### PR TITLE
[#92]  All indentations should be two spaces

### PR DESCRIPTION
**Pull request by kammanz**
Reformatted code to 2 spaces

What's competed:

- Js and scss files are reformatted to 2 spaces
- Code formatted with prettify

### CODE REVIEW

**Comment by kammanz** [comment]
Ready for review.
- I added prettify, which has made some minor reformats to the code. Personally I like it and it looks more readable, let me know if any issues.

**Review by Tumne — APPROVED** [review]
Looks good to me. 

Waiting to merge once #99 is merged into master and the conflicts below are resolved.

**Review by Tumne — CHANGES_REQUESTED** [review]
There are a lot of double quotes in the scss files where it should be single quotes. Please change

**Comment by kammanz** [comment]
Ready for review.

**Pull request merged**
